# Generated by Django 2.2.1 on 2019-09-02 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_at', models.DateField(verbose_name='购买时间')),
                ('price', models.CharField(blank=True, max_length=32, null=True, verbose_name='价格')),
                ('recipient_at', models.DateField(verbose_name='领用时间')),
                ('sn', models.CharField(max_length=32, verbose_name='资产编号')),
                ('supplier', models.IntegerField(choices=[(1, 'N'), (2, '戴尔'), (3, '苹果')], default=3, verbose_name='供应商')),
                ('after_sales', models.CharField(blank=True, max_length=128, null=True, verbose_name='售后联系方式')),
                ('status', models.IntegerField(choices=[(1, '空闲'), (2, '保修'), (3, '报废')], default=1, verbose_name='状态')),
                ('note', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='备注')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Models', verbose_name='型号')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Employee', verbose_name='领用人')),
            ],
        ),
    ]
