# Generated by Django 2.2.1 on 2019-09-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='recipient_at',
            field=models.DateField(blank=True, null=True, verbose_name='领用时间'),
        ),
    ]
