# Generated by Django 2.2.1 on 2019-07-10 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_action_permission_permission2action_permission2action2role_role_user_user2role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': '角色表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户表'},
        ),
    ]
