# Generated by Django 2.2.1 on 2019-09-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190902_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.IntegerField(choices=[(1, '空闲'), (2, '使用'), (3, '报废')], default=1, verbose_name='状态'),
        ),
    ]
