# Generated by Django 2.2.1 on 2019-10-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190930_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='note',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='备注'),
        ),
    ]
