# Generated by Django 2.2.1 on 2019-08-24 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190710_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(blank=True, max_length=32, null=True)),
                ('mem', models.CharField(blank=True, max_length=32, null=True, verbose_name='内存')),
                ('harddisk', models.CharField(blank=True, max_length=32, null=True, verbose_name='硬盘')),
                ('gpu', models.CharField(blank=True, max_length=32, null=True, verbose_name='显卡')),
                ('screen', models.IntegerField(blank=True, choices=[('1', '23"'), ('2', '24"')], null=True, verbose_name='显示屏')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.CharField(max_length=32, verbose_name='价格')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='类型')),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_name', to='api.Type', verbose_name='型号')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='员工姓名')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Department', verbose_name='部门')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('purchase_at', models.DateTimeField(verbose_name='购买时间')),
                ('recipient_at', models.DateTimeField(verbose_name='领用时间')),
                ('sn', models.CharField(max_length=32, verbose_name='资产编号')),
                ('supplier', models.IntegerField(blank=True, choices=[('1', '戴尔'), ('2', '苹果')], null=True, verbose_name='供应商')),
                ('after_sales', models.CharField(blank=True, max_length=128, null=True, verbose_name='售后联系方式')),
                ('note', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('configure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Configuration', verbose_name='配置')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Models', verbose_name='型号')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Employee', verbose_name='领用人')),
            ],
        ),
    ]
