# Generated by Django 2.2.1 on 2019-08-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_asset_configuration_department_employee_models_price_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name_plural': '设备'},
        ),
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name_plural': '配置'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': '部门'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': '员工'},
        ),
        migrations.AlterModelOptions(
            name='models',
            options={'verbose_name_plural': '型号'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name_plural': '价格'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name_plural': '类别'},
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=32, verbose_name='类别'),
        ),
    ]
