# Generated by Django 2.2.1 on 2019-08-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190824_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='configuration',
            options={},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='models',
            options={},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={},
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=32, verbose_name='类型'),
        ),
    ]
