# Generated by Django 2.2.1 on 2019-08-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190824_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='价格'),
        ),
    ]
