# Generated by Django 2.2.1 on 2019-08-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190824_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='supplier',
            field=models.IntegerField(blank=True, choices=[(1, '戴尔'), (2, '苹果')], null=True, verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='screen',
            field=models.IntegerField(blank=True, choices=[(1, '23"'), (2, '24"')], null=True, verbose_name='显示屏'),
        ),
    ]
