# Generated by Django 2.2.1 on 2019-08-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190824_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchase_at',
            field=models.DateField(verbose_name='购买时间'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='recipient_at',
            field=models.DateField(verbose_name='领用时间'),
        ),
    ]
