# Generated by Django 2.2.1 on 2019-08-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190824_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.IntegerField(default=1, verbose_name=((1, '空闲'), (2, '保修'), (3, '报废'))),
        ),
    ]
