# Generated by Django 2.2.1 on 2019-08-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.IntegerField(choices=[(1, '空闲'), (2, '保修'), (3, '报废')], default=1),
        ),
    ]
