# Generated by Django 2.2.1 on 2019-08-25 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190824_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_name', to='api.Type', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=32, verbose_name='类别'),
        ),
    ]
