# Generated by Django 2.2.1 on 2019-08-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190825_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='note',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.IntegerField(choices=[(1, '空闲'), (2, '保修'), (3, '报废')], default=1, verbose_name='状态'),
        ),
    ]
