# Generated by Django 2.2.1 on 2019-08-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190827_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='supplier',
            field=models.IntegerField(choices=[(1, '戴尔'), (2, '苹果'), (3, 'N')], default=3, verbose_name='供应商'),
        ),
    ]
