# Generated by Django 2.2.1 on 2019-08-27 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190827_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='configure',
        ),
        migrations.AddField(
            model_name='models',
            name='configure',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Configuration', verbose_name='配置'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='supplier',
            field=models.IntegerField(choices=[(1, 'N'), (2, '戴尔'), (3, '苹果')], default=3, verbose_name='供应商'),
        ),
    ]
