# Generated by Django 2.2.1 on 2019-08-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190827_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='screen',
            field=models.IntegerField(blank=True, max_length=32, null=True, verbose_name='显示器'),
        ),
    ]
