# Generated by Django 2.2.1 on 2019-08-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190828_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='screen',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='显示器'),
        ),
    ]
